# Generated by Django 5.0.3 on 2024-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp1', '0006_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('K', 'Khalti Payment')], default='C', max_length=1),
        ),
    ]
