# Generated by Django 5.0.3 on 2024-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Cancelled', 'Order Cancelled'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order pending', 'Order Pending')], max_length=50),
        ),
    ]
