# Generated by Django 5.0.3 on 2024-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Cancelled', 'Order Cancelled'), ('Order Completed', 'Order Completed'), ('Order pending', 'Order Pending'), ('Order Received', 'Order Received')], max_length=50),
        ),
    ]
