# Generated by Django 5.0.3 on 2024-04-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order pending', 'Order Pending'), ('On the way', 'On the way'), ('Order Received', 'Order Received'), ('Order Cancelled', 'Order Cancelled')], max_length=50),
        ),
    ]
